### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Owstin** [Owstin/scrambo#3]
- [x] Rewrite scrambo in typescrpt

~~- [ ] Rewrite scramblers in typescript (is this even possible/is it even worth it?)~~

- [ ] Create a simpler scrambler api

- [ ] Use [random-int](https://github.com/lgarron/random-int-js/blob/master/src/get-random-values.ts) for random numbers

- [ ] Leverage some of the work done by [cs0x7f](https://github.com/cs0x7f/cstimer/tree/master/src/js/scramble)

- [ ] es2015+ on scramblers

- [x] Create simpler way to add new scramblers (see [Scramblr](https://github.com/Owstin/scramblr/blob/master/lib/scramblers/index.js#L45))

- [ ] Better cli?

- [ ] Check different bundler (fusebox, rollup, others?)

- [x] Convert unit tests to jest
